apiVersion: v1
kind: Namespace
metadata:
  name: k8s-reverseproxy-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-reverseproxy-operator
  namespace: k8s-reverseproxy-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: k8s-reverseproxy-operator
  template:
    metadata:
      labels:
        app: k8s-reverseproxy-operator
    spec:
      serviceAccountName: k8s-reverseproxy-operator
      containers:
        - name: k8s-reverseproxy-operator
          image: ghcr.io/alirionx/k8s-reverseproxy-operator:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "64Mi"
              cpu: "125m"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-reverseproxy-operator
  namespace: k8s-reverseproxy-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-reverseproxy-operator
rules:
  - apiGroups: [app-scape.dev]
    resources: [reverseproxyentrys]
    verbs: [list, watch, patch, get]

  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  - apiGroups: [""]
    resources: [endpoints, services ]
    verbs: ["*"]

  - apiGroups: ["networking.k8s.io"]
    resources: [ingresses]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-reverseproxy-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-reverseproxy-operator
subjects:
  - kind: ServiceAccount
    name: k8s-reverseproxy-operator
    namespace: k8s-reverseproxy-operator


